/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _authenticatedRouteImport } from './routes/__authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _authenticatedAppRouteImport } from './routes/__authenticated/app'
import { Route as _authenticatedAppTrashRouteImport } from './routes/__authenticated/app/trash'
import { Route as _authenticatedAppTagsRouteImport } from './routes/__authenticated/app/tags'
import { Route as _authenticatedAppRecentRouteImport } from './routes/__authenticated/app/recent'
import { Route as _authenticatedAppFavoritesRouteImport } from './routes/__authenticated/app/favorites'
import { Route as _authenticatedAppCollectionsRouteImport } from './routes/__authenticated/app/collections'
import { Route as _authenticatedAppBookmarksRouteImport } from './routes/__authenticated/app/bookmarks'

const _authenticatedRoute = _authenticatedRouteImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedAppRoute = _authenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedAppTrashRoute = _authenticatedAppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => _authenticatedAppRoute,
} as any)
const _authenticatedAppTagsRoute = _authenticatedAppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => _authenticatedAppRoute,
} as any)
const _authenticatedAppRecentRoute = _authenticatedAppRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => _authenticatedAppRoute,
} as any)
const _authenticatedAppFavoritesRoute =
  _authenticatedAppFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => _authenticatedAppRoute,
  } as any)
const _authenticatedAppCollectionsRoute =
  _authenticatedAppCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => _authenticatedAppRoute,
  } as any)
const _authenticatedAppBookmarksRoute =
  _authenticatedAppBookmarksRouteImport.update({
    id: '/bookmarks',
    path: '/bookmarks',
    getParentRoute: () => _authenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof _authenticatedAppRouteWithChildren
  '/app/bookmarks': typeof _authenticatedAppBookmarksRoute
  '/app/collections': typeof _authenticatedAppCollectionsRoute
  '/app/favorites': typeof _authenticatedAppFavoritesRoute
  '/app/recent': typeof _authenticatedAppRecentRoute
  '/app/tags': typeof _authenticatedAppTagsRoute
  '/app/trash': typeof _authenticatedAppTrashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof _authenticatedAppRouteWithChildren
  '/app/bookmarks': typeof _authenticatedAppBookmarksRoute
  '/app/collections': typeof _authenticatedAppCollectionsRoute
  '/app/favorites': typeof _authenticatedAppFavoritesRoute
  '/app/recent': typeof _authenticatedAppRecentRoute
  '/app/tags': typeof _authenticatedAppTagsRoute
  '/app/trash': typeof _authenticatedAppTrashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__authenticated': typeof _authenticatedRouteWithChildren
  '/__authenticated/app': typeof _authenticatedAppRouteWithChildren
  '/__authenticated/app/bookmarks': typeof _authenticatedAppBookmarksRoute
  '/__authenticated/app/collections': typeof _authenticatedAppCollectionsRoute
  '/__authenticated/app/favorites': typeof _authenticatedAppFavoritesRoute
  '/__authenticated/app/recent': typeof _authenticatedAppRecentRoute
  '/__authenticated/app/tags': typeof _authenticatedAppTagsRoute
  '/__authenticated/app/trash': typeof _authenticatedAppTrashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/bookmarks'
    | '/app/collections'
    | '/app/favorites'
    | '/app/recent'
    | '/app/tags'
    | '/app/trash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/bookmarks'
    | '/app/collections'
    | '/app/favorites'
    | '/app/recent'
    | '/app/tags'
    | '/app/trash'
  id:
    | '__root__'
    | '/'
    | '/__authenticated'
    | '/__authenticated/app'
    | '/__authenticated/app/bookmarks'
    | '/__authenticated/app/collections'
    | '/__authenticated/app/favorites'
    | '/__authenticated/app/recent'
    | '/__authenticated/app/tags'
    | '/__authenticated/app/trash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _authenticatedRoute: typeof _authenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/app': {
      id: '/__authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof _authenticatedAppRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/app/trash': {
      id: '/__authenticated/app/trash'
      path: '/trash'
      fullPath: '/app/trash'
      preLoaderRoute: typeof _authenticatedAppTrashRouteImport
      parentRoute: typeof _authenticatedAppRoute
    }
    '/__authenticated/app/tags': {
      id: '/__authenticated/app/tags'
      path: '/tags'
      fullPath: '/app/tags'
      preLoaderRoute: typeof _authenticatedAppTagsRouteImport
      parentRoute: typeof _authenticatedAppRoute
    }
    '/__authenticated/app/recent': {
      id: '/__authenticated/app/recent'
      path: '/recent'
      fullPath: '/app/recent'
      preLoaderRoute: typeof _authenticatedAppRecentRouteImport
      parentRoute: typeof _authenticatedAppRoute
    }
    '/__authenticated/app/favorites': {
      id: '/__authenticated/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof _authenticatedAppFavoritesRouteImport
      parentRoute: typeof _authenticatedAppRoute
    }
    '/__authenticated/app/collections': {
      id: '/__authenticated/app/collections'
      path: '/collections'
      fullPath: '/app/collections'
      preLoaderRoute: typeof _authenticatedAppCollectionsRouteImport
      parentRoute: typeof _authenticatedAppRoute
    }
    '/__authenticated/app/bookmarks': {
      id: '/__authenticated/app/bookmarks'
      path: '/bookmarks'
      fullPath: '/app/bookmarks'
      preLoaderRoute: typeof _authenticatedAppBookmarksRouteImport
      parentRoute: typeof _authenticatedAppRoute
    }
  }
}

interface _authenticatedAppRouteChildren {
  _authenticatedAppBookmarksRoute: typeof _authenticatedAppBookmarksRoute
  _authenticatedAppCollectionsRoute: typeof _authenticatedAppCollectionsRoute
  _authenticatedAppFavoritesRoute: typeof _authenticatedAppFavoritesRoute
  _authenticatedAppRecentRoute: typeof _authenticatedAppRecentRoute
  _authenticatedAppTagsRoute: typeof _authenticatedAppTagsRoute
  _authenticatedAppTrashRoute: typeof _authenticatedAppTrashRoute
}

const _authenticatedAppRouteChildren: _authenticatedAppRouteChildren = {
  _authenticatedAppBookmarksRoute: _authenticatedAppBookmarksRoute,
  _authenticatedAppCollectionsRoute: _authenticatedAppCollectionsRoute,
  _authenticatedAppFavoritesRoute: _authenticatedAppFavoritesRoute,
  _authenticatedAppRecentRoute: _authenticatedAppRecentRoute,
  _authenticatedAppTagsRoute: _authenticatedAppTagsRoute,
  _authenticatedAppTrashRoute: _authenticatedAppTrashRoute,
}

const _authenticatedAppRouteWithChildren =
  _authenticatedAppRoute._addFileChildren(_authenticatedAppRouteChildren)

interface _authenticatedRouteChildren {
  _authenticatedAppRoute: typeof _authenticatedAppRouteWithChildren
}

const _authenticatedRouteChildren: _authenticatedRouteChildren = {
  _authenticatedAppRoute: _authenticatedAppRouteWithChildren,
}

const _authenticatedRouteWithChildren = _authenticatedRoute._addFileChildren(
  _authenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _authenticatedRoute: _authenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
